---
run:
  timeout: 3m
  build-tags:
    - integration

linters:
  enable:
    - misspell
    - goimports
    - revive
    - gofmt
    - godot

issues:
  exclude-rules:
    # Exclude unused parameter checks from the noop logger for readability
    - path: internal/log/log.go
      linters:
        - revive
      text: "unused-parameter: parameter '(\\w+)' seems to be unused, .*"
